import { bodyParts as CENTRAL_BODY_PARTS } from "../data/bodyParts.js";
import { exercises as CENTRAL_EXERCISES } from "../data/exercises.js";

const EXERCISE_CATEGORIES = [
  {
    id: "upper-body",
    name: "Upper Body",
    description: "Build pressing, pulling and arm strength.",
    icon: "💪",
    exerciseCount: 16,
  },
  {
    id: "lower-body",
    name: "Lower Body",
    description: "Strengthen legs, glutes and lower-body control.",
    icon: "🦵",
    exerciseCount: 10,
  },
  {
    id: "core",
    name: "Core",
    description: "Develop abs, obliques and lower back stability.",
    icon: "🧠",
    exerciseCount: 11,
  },
];

const EXERCISE_MUSCLES = [
  { id: "chest", name: "Chest", categoryId: "upper-body", description: "Pressing and pushing strength." },
  { id: "back", name: "Back", categoryId: "upper-body", description: "Pulling strength and posture." },
  { id: "shoulders", name: "Shoulders", categoryId: "upper-body", description: "Overhead and stability training." },
  { id: "biceps", name: "Biceps", categoryId: "upper-body", description: "Arm flexion and grip support." },
  { id: "triceps", name: "Triceps", categoryId: "upper-body", description: "Extension power and pressing support." },
  { id: "quadriceps", name: "Quadriceps", categoryId: "lower-body", description: "Front-leg strength and knee control." },
  { id: "hamstrings", name: "Hamstrings", categoryId: "lower-body", description: "Hip hinge strength and posterior chain." },
  { id: "calves", name: "Calves", categoryId: "lower-body", description: "Ankle stability and lower-leg power." },
  { id: "abs", name: "Abs", categoryId: "core", description: "Midline control and abdominal strength." },
  { id: "obliques", name: "Obliques", categoryId: "core", description: "Twisting strength and side stability." },
  { id: "lower-back", name: "Lower Back", categoryId: "core", description: "Spinal support and posterior control." },
];

const LEGACY_BODY_PARTS = [
  { id: "shoulders", name: "Shoulders", description: "Build strong, stable shoulders for pressing and overhead strength." },
  { id: "chest", name: "Chest", description: "Target chest strength and pressing power with compound movements." },
  { id: "back", name: "Back", description: "Build pulling strength and posture with lat and upper-back exercises." },
  { id: "arms", name: "Arms", description: "Train biceps, triceps and arm hypertrophy with isolation and compound lifts." },
  { id: "forearms", name: "Forearms", description: "Improve grip strength and forearm conditioning." },
  { id: "core", name: "Core", description: "Strengthen abs and midline stability for all movements." },
  { id: "glutes", name: "Glutes", description: "Powerful glutes support posture, hips, and lower-body strength." },
  { id: "legs", name: "Legs", description: "Build lower-body strength, endurance, and stability." },
  { id: "calves", name: "Calves", description: "Train calf muscles for better balance and lower-leg conditioning." },
  { id: "grip", name: "Grip", description: "Improve finger and hand strength for better overall control." },
];

const EXERCISES = [
  {
    id: "bench-press",
    name: "Bench Press",
    description: "Press the bar from your chest while keeping shoulders stable.",
    instructions: "Retract your shoulder blades, lower the bar to your chest, and press back up with control.",
    difficulty: "Intermediate",
    equipment: "Barbell",
    target_muscles: "Chest",
    categoryId: "upper-body",
    muscleId: "chest",
    bodyPartId: "chest",
    workoutType: "GYM",
    sets: "3",
    reps: "8–12",
    rest: "90s",
    formTips: ["Keep your feet planted and ribs down.", "Press through the chest while keeping your elbows slightly tucked."],
    commonMistakes: ["Lifting hips off the bench.", "Flaring the elbows excessively."],
    safetyTip: "Warm up shoulders and avoid bouncing the bar off the chest.",
  },
  {
    id: "push-up",
    name: "Push-Up",
    description: "Use bodyweight to train chest, shoulders, and triceps.",
    instructions: "Keep a straight line from head to heels, lower your chest, then press back up.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Chest",
    categoryId: "upper-body",
    muscleId: "chest",
    bodyPartId: "chest",
    workoutType: "HOME",
    sets: "3",
    reps: "10–15",
    rest: "60s",
    formTips: ["Brace your core and keep your spine neutral.", "Lower until your chest is close to the floor."],
    commonMistakes: ["Dropping the hips.", "Flaring the elbows too wide."],
    safetyTip: "Keep shoulder blades stable and avoid collapsing at the bottom.",
  },
  {
    id: "chest-flyes",
    name: "Chest Flyes",
    description: "Open the chest with a controlled arc using dumbbells or cables.",
    instructions: "Keep a slight elbow bend and move the weights out wide, then bring them together over your chest.",
    difficulty: "Intermediate",
    equipment: "Dumbbells or cable machine",
    target_muscles: "Chest",
    categoryId: "upper-body",
    muscleId: "chest",
    bodyPartId: "chest",
    workoutType: "GYM",
    sets: "3",
    reps: "10–14",
    rest: "75s",
    formTips: ["Keep tension on the chest the entire time.", "Avoid letting the elbows drop too far below shoulder level."],
    commonMistakes: ["Locking the elbows.", "Using too much weight and losing control."],
    safetyTip: "Move in a smooth, controlled motion and stop if the shoulder joint feels unstable.",
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    description: "Pull your body up until your chin clears the bar.",
    instructions: "Start from a full hang, engage your lats, and pull the bar to chest level.",
    difficulty: "Advanced",
    equipment: "Pull-up bar",
    target_muscles: "Back",
    categoryId: "upper-body",
    muscleId: "back",
    bodyPartId: "back",
    workoutType: "GYM",
    sets: "4",
    reps: "6–10",
    rest: "90s",
    formTips: ["Keep your shoulders engaged and avoid swinging.", "Control the descent back to a full hang."],
    commonMistakes: ["Kipping excessively.", "Shrugging the shoulders."],
    safetyTip: "Use a band for assistance if you cannot maintain strict form.",
  },
  {
    id: "rows",
    name: "Rows",
    description: "Pull weight toward your torso to build mid-back strength.",
    instructions: "Keep your torso steady and drive your elbows back while squeezing your shoulder blades.",
    difficulty: "Intermediate",
    equipment: "Dumbbells or barbell",
    target_muscles: "Back",
    categoryId: "upper-body",
    muscleId: "back",
    bodyPartId: "back",
    workoutType: "GYM",
    sets: "3",
    reps: "8–12",
    rest: "75s",
    formTips: ["Keep a slight hinge in the hips.", "Lead with the elbows rather than the hands."],
    commonMistakes: ["Rounding the lower back.", "Using momentum to lift the weight."],
    safetyTip: "Keep your spine neutral and avoid jerking the weight.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    description: "Train your lats and upper back on a cable machine.",
    instructions: "Pull the bar to your upper chest and lower it with control.",
    difficulty: "Beginner",
    equipment: "Cable machine",
    target_muscles: "Back",
    categoryId: "upper-body",
    muscleId: "back",
    bodyPartId: "back",
    workoutType: "GYM",
    sets: "3",
    reps: "10–14",
    rest: "75s",
    formTips: ["Keep your chest upright.", "Lead with your elbows, pulling them down and back."],
    commonMistakes: ["Pulling behind the neck.", "Leaning too far back."],
    safetyTip: "Pause briefly at the bottom and maintain a stable torso.",
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    description: "Press weight overhead with core stability.",
    instructions: "Drive the weight up in a straight line while bracing your midsection.",
    difficulty: "Intermediate",
    equipment: "Dumbbells or barbell",
    target_muscles: "Shoulders",
    categoryId: "upper-body",
    muscleId: "shoulders",
    bodyPartId: "shoulders",
    workoutType: "GYM",
    sets: "3",
    reps: "8–12",
    rest: "90s",
    formTips: ["Keep your head neutral.", "Avoid arching your lower back."],
    commonMistakes: ["Flared elbows.", "Leaning back too much."],
    safetyTip: "Use a lighter weight if your spine starts to overarch.",
  },
  {
    id: "lateral-raises",
    name: "Lateral Raises",
    description: "Raise the arms to shoulder height with a slight bend.",
    instructions: "Keep elbows soft and lift the weights out to your sides.",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    target_muscles: "Shoulders",
    categoryId: "upper-body",
    muscleId: "shoulders",
    bodyPartId: "shoulders",
    workoutType: "GYM",
    sets: "3",
    reps: "10–15",
    rest: "60s",
    formTips: ["Keep motion smooth.", "Avoid swinging the weights."],
    commonMistakes: ["Using too much momentum.", "Shrugging the shoulders."],
    safetyTip: "Pause briefly at the top and maintain shoulder control.",
  },
  {
    id: "front-raise",
    name: "Front Raise",
    description: "Lift the weight in front of your body with control.",
    instructions: "Raise the dumbbells until they reach shoulder height.",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    target_muscles: "Shoulders",
    categoryId: "upper-body",
    muscleId: "shoulders",
    bodyPartId: "shoulders",
    workoutType: "GYM",
    sets: "3",
    reps: "10–14",
    rest: "60s",
    formTips: ["Keep wrists straight.", "Move through a controlled tempo."],
    commonMistakes: ["Using back momentum.", "Lifting too high."],
    safetyTip: "Maintain shoulder joint stability throughout.",
  },
  {
    id: "pike-press",
    name: "Pike Press",
    description: "Use your bodyweight to train shoulder pressing strength at home.",
    instructions: "Start in a pike position, lower your head toward the floor, then press back up.",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    target_muscles: "Shoulders",
    categoryId: "upper-body",
    muscleId: "shoulders",
    bodyPartId: "shoulders",
    workoutType: "HOME",
    sets: "3",
    reps: "8–12",
    rest: "60s",
    formTips: ["Keep your hips high.", "Bend your elbows straight back."],
    commonMistakes: ["Letting the hips sag.", "Flaring the elbows."],
    safetyTip: "Control the descent and avoid loading the neck.",
  },
  {
    id: "shoulder-taps",
    name: "Shoulder Taps",
    description: "Build shoulder stability and core control with alternate taps.",
    instructions: "Hold a plank, then lift one hand to tap the opposite shoulder while keeping hips stable.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Shoulders",
    categoryId: "upper-body",
    muscleId: "shoulders",
    bodyPartId: "shoulders",
    workoutType: "HOME",
    sets: "3",
    reps: "12 each side",
    rest: "45s",
    formTips: ["Keep your hips square.", "Move slowly and keep tension through the shoulders."],
    commonMistakes: ["Dropping the hips.", "Rotating the shoulders."],
    safetyTip: "Maintain a strong plank shape for the full set.",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    description: "Curl the weights with a neutral grip to target the biceps and forearms.",
    instructions: "Curl the dumbbells up while keeping your elbows close to your body.",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    target_muscles: "Biceps",
    categoryId: "upper-body",
    muscleId: "biceps",
    bodyPartId: "arms",
    workoutType: "GYM",
    sets: "3",
    reps: "10–12",
    rest: "60s",
    formTips: ["Keep wrists steady.", "Squeeze the biceps at the top."],
    commonMistakes: ["Swinging the torso.", "Allowing elbows to drift forward."],
    safetyTip: "Use a controlled tempo and avoid heavy momentum.",
  },
  {
    id: "chin-up",
    name: "Chin-Up",
    description: "Pull your body up with an underhand grip to train the biceps and back.",
    instructions: "Start from a dead hang and pull until your chin clears the bar.",
    difficulty: "Advanced",
    equipment: "Pull-up bar",
    target_muscles: "Biceps",
    categoryId: "upper-body",
    muscleId: "biceps",
    bodyPartId: "arms",
    workoutType: "HOME",
    sets: "3",
    reps: "6–10",
    rest: "90s",
    formTips: ["Keep your body straight.", "Pull with the elbows, not the wrists."],
    commonMistakes: ["Kipping the legs.", "Curling the shoulders forward."],
    safetyTip: "Use a band for assistance if you cannot maintain strict form.",
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    description: "Use cables to isolate the triceps with a straight-arm extension.",
    instructions: "Pull the handle down until your arms are fully extended.",
    difficulty: "Beginner",
    equipment: "Cable machine",
    target_muscles: "Triceps",
    categoryId: "upper-body",
    muscleId: "triceps",
    bodyPartId: "arms",
    workoutType: "GYM",
    sets: "3",
    reps: "10–14",
    rest: "60s",
    formTips: ["Keep your elbows fixed by your sides.", "Fully extend the arms without locking the elbows."],
    commonMistakes: ["Using the shoulders.", "Allowing the elbows to flare."],
    safetyTip: "Control the weight and keep tension on the triceps.",
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    description: "Train the triceps with a lying extension movement.",
    instructions: "Lower the bar or dumbbells toward your forehead, then extend the arms back up.",
    difficulty: "Intermediate",
    equipment: "Barbell or dumbbells",
    target_muscles: "Triceps",
    categoryId: "upper-body",
    muscleId: "triceps",
    bodyPartId: "arms",
    workoutType: "GYM",
    sets: "3",
    reps: "8–12",
    rest: "75s",
    formTips: ["Keep your upper arms still.", "Control the descent and avoid bouncing."],
    commonMistakes: ["Letting the elbows drift apart.", "Dropping the weights too quickly."],
    safetyTip: "Use a spotter with heavy loads and maintain control.",
  },
  {
    id: "tricep-dip-home",
    name: "Tricep Dip",
    description: "Use a chair or bench to work the triceps and chest.",
    instructions: "Lower until your elbows are about 90 degrees, then push back up.",
    difficulty: "Intermediate",
    equipment: "Bench or chair",
    target_muscles: "Triceps",
    categoryId: "upper-body",
    muscleId: "triceps",
    bodyPartId: "arms",
    workoutType: "HOME",
    sets: "3",
    reps: "10–14",
    rest: "60s",
    formTips: ["Keep your shoulders down.", "Tuck the elbows slightly behind you."],
    commonMistakes: ["Shoulders creeping up.", "Locking the elbows too early."],
    safetyTip: "Use a stable surface and avoid dipping too low.",
  },
  {
    id: "squat",
    name: "Squat",
    description: "Bend at the hips and knees while keeping your chest upright.",
    instructions: "Drive through your heels and keep your knees tracking over your toes.",
    difficulty: "Beginner",
    equipment: "Bodyweight or barbell",
    target_muscles: "Quadriceps",
    categoryId: "lower-body",
    muscleId: "quadriceps",
    bodyPartId: "legs",
    workoutType: "HOME",
    sets: "4",
    reps: "10–15",
    rest: "75s",
    formTips: ["Keep weight in your heels.", "Sit back into the movement."],
    commonMistakes: ["Knees collapsing inward.", "Rising onto the toes."],
    safetyTip: "Maintain a neutral spine and move with control.",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    description: "Isolate the quads with a machine extension movement.",
    instructions: "Extend your legs up until they are nearly straight.",
    difficulty: "Beginner",
    equipment: "Leg extension machine",
    target_muscles: "Quadriceps",
    categoryId: "lower-body",
    muscleId: "quadriceps",
    bodyPartId: "legs",
    workoutType: "GYM",
    sets: "3",
    reps: "12–15",
    rest: "60s",
    formTips: ["Keep your core engaged.", "Avoid locking out the knees."],
    commonMistakes: ["Using momentum.", "Lifting the hips."],
    safetyTip: "Adjust the pad so it sits just above your ankles.",
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    description: "Step forward and lower your back knee toward the floor.",
    instructions: "Keep your front knee behind your toes and maintain a tall torso.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Quadriceps",
    categoryId: "lower-body",
    muscleId: "quadriceps",
    bodyPartId: "legs",
    workoutType: "HOME",
    sets: "3",
    reps: "10–12 per leg",
    rest: "60s",
    formTips: ["Keep your front knee aligned.", "Step with purpose and lower under control."],
    commonMistakes: ["Leaning forward.", "Letting the knee collapse inward."],
    safetyTip: "Use a mirror if available to check your alignment.",
  },
  {
    id: "deadlift",
    name: "Deadlift",
    description: "Lift the weight from the floor using a strong hip hinge.",
    instructions: "Keep your back flat and drive through the heels as you stand tall.",
    difficulty: "Advanced",
    equipment: "Barbell",
    target_muscles: "Hamstrings",
    categoryId: "lower-body",
    muscleId: "hamstrings",
    bodyPartId: "legs",
    workoutType: "GYM",
    sets: "4",
    reps: "6–10",
    rest: "120s",
    formTips: ["Keep the bar close to your legs.", "Drive your hips forward while maintaining a neutral spine."],
    commonMistakes: ["Rounding the back.", "Shrugging the shoulders."],
    safetyTip: "Use a weight you can control for every rep.",
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    description: "Train the hamstrings with a lying or seated curl machine.",
    instructions: "Curl the pad toward your glutes and lower with control.",
    difficulty: "Beginner",
    equipment: "Leg curl machine",
    target_muscles: "Hamstrings",
    categoryId: "lower-body",
    muscleId: "hamstrings",
    bodyPartId: "legs",
    workoutType: "GYM",
    sets: "3",
    reps: "10–14",
    rest: "60s",
    formTips: ["Keep your hips planted.", "Avoid snapping the weight back down."],
    commonMistakes: ["Lifting the hips.", "Using too much momentum."],
    safetyTip: "Focus on a slow, controlled squeeze at the top.",
  },
  {
    id: "good-morning",
    name: "Good Morning",
    description: "Hinge at the hips to train the posterior chain.",
    instructions: "Keep your spine neutral and push your hips back while lowering your torso.",
    difficulty: "Intermediate",
    equipment: "Barbell",
    target_muscles: "Hamstrings",
    categoryId: "lower-body",
    muscleId: "hamstrings",
    bodyPartId: "legs",
    workoutType: "GYM",
    sets: "3",
    reps: "8–12",
    rest: "90s",
    formTips: ["Keep a soft bend in the knees.", "Stop when your back begins to round."],
    commonMistakes: ["Rounding the lower back.", "Going too low too fast."],
    safetyTip: "Use lighter weight until your hinge pattern is solid.",
  },
  {
    id: "standing-calf-raises",
    name: "Standing Calf Raises",
    description: "Raise your heels to stand on your toes and lower with control.",
    instructions: "Keep your core tight and move through the full ankle range.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Calves",
    categoryId: "lower-body",
    muscleId: "calves",
    bodyPartId: "calves",
    workoutType: "HOME",
    sets: "4",
    reps: "15–20",
    rest: "45s",
    formTips: ["Keep your toes pointed forward.", "Pause briefly at the top."],
    commonMistakes: ["Bouncing at the bottom.", "Using too much speed."],
    safetyTip: "Use a step or platform for a longer range if comfortable.",
  },
  {
    id: "seated-calf-raises",
    name: "Seated Calf Raises",
    description: "Train your calves from a seated position for targeted activation.",
    instructions: "Press through the balls of your feet and lower slowly.",
    difficulty: "Beginner",
    equipment: "Machine or dumbbells",
    target_muscles: "Calves",
    categoryId: "lower-body",
    muscleId: "calves",
    bodyPartId: "calves",
    workoutType: "GYM",
    sets: "4",
    reps: "15–20",
    rest: "45s",
    formTips: ["Keep toes pointed forward.", "Fully stretch the calves at the bottom."],
    commonMistakes: ["Bouncing at the top.", "Lifting the heels off the platform."],
    safetyTip: "Control each rep and keep the knee stable.",
  },
  {
    id: "crunches",
    name: "Crunches",
    description: "Raise your upper body with a controlled abdominal contraction.",
    instructions: "Keep your lower back on the floor and lift with the abs.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "15–20",
    rest: "45s",
    formTips: ["Lead with the chest, not the neck.", "Keep the lower back connected."],
    commonMistakes: ["Pulling on the neck.", "Using momentum."],
    safetyTip: "Use a small range of motion if your neck feels strained.",
  },
  {
    id: "planks",
    name: "Planks",
    description: "Hold a straight-body position to build core stability.",
    instructions: "Keep your hips level and core engaged while holding the position.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "45–60s",
    rest: "45s",
    formTips: ["Keep your shoulders over your elbows.", "Maintain a straight line from head to heels."],
    commonMistakes: ["Dropping the hips.", "Raising the glutes too high."],
    safetyTip: "Stop if you feel lower-back pain.",
  },
  {
    id: "leg-raises",
    name: "Leg Raises",
    description: "Lift your legs up while keeping your lower back pressed into the floor.",
    instructions: "Keep your legs straight and lower them slowly with control.",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "10–15",
    rest: "45s",
    formTips: ["Press your lower back into the floor.", "Avoid swinging the legs."],
    commonMistakes: ["Arching the lower back.", "Using momentum."],
    safetyTip: "Bend the knees slightly if the lower back lifts.",
  },
  {
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    description: "Rotate through the torso for abs and oblique engagement.",
    instructions: "Alternate elbow-to-opposite-knee connections with a controlled twist.",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "20 total",
    rest: "45s",
    formTips: ["Keep your lower back down.", "Rotate from the torso."],
    commonMistakes: ["Jerking the neck.", "Letting the lower back arch."],
    safetyTip: "Move with control and avoid fast, sloppy reps.",
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    description: "Move your knees toward your chest from a plank position.",
    instructions: "Drive each knee forward with a steady core and minimal hip movement.",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "30 total",
    rest: "45s",
    formTips: ["Keep hips stable.", "Maintain a strong plank position."],
    commonMistakes: ["Piking the hips.", "Bouncing the back."],
    safetyTip: "Keep the core engaged and pace consistent.",
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    description: "Use cables to load the abs with a controlled crunch.",
    instructions: "Kneel and pull the cable down while curling your torso.",
    difficulty: "Intermediate",
    equipment: "Cable machine",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "GYM",
    sets: "3",
    reps: "12–15",
    rest: "60s",
    formTips: ["Move with control.", "Keep the tension on your abs."],
    commonMistakes: ["Pulling with the arms.", "Using too much range."],
    safetyTip: "Keep the movement slow and the core engaged.",
  },
  {
    id: "weighted-crunch",
    name: "Weighted Crunch",
    description: "Add resistance to crunches using a plate or dumbbell.",
    instructions: "Hold the weight over your chest and curl your torso upward.",
    difficulty: "Intermediate",
    equipment: "Weight plate or dumbbell",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "GYM",
    sets: "3",
    reps: "10–14",
    rest: "60s",
    formTips: ["Keep your lower back down.", "Move from the chest, not the neck."],
    commonMistakes: ["Lifting the lower back.", "Pulling on the neck."],
    safetyTip: "Choose a weight that allows clean movement.",
  },
  {
    id: "machine-ab-crunch",
    name: "Machine Ab Crunch",
    description: "Use an ab machine to train the core with guided resistance.",
    instructions: "Crunch the weight forward while keeping your hips stable.",
    difficulty: "Beginner",
    equipment: "Ab machine",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "GYM",
    sets: "3",
    reps: "12–15",
    rest: "60s",
    formTips: ["Keep your core tight.", "Control the return to the start position."],
    commonMistakes: ["Using momentum.", "Letting the hips shift."],
    safetyTip: "Select a moderate weight to maintain a full range.",
  },
  {
    id: "hanging-leg-raises",
    name: "Hanging Leg Raises",
    description: "Lift your legs from a hanging position to train the lower abs.",
    instructions: "Keep your torso still and lift the legs until they reach hip height.",
    difficulty: "Advanced",
    equipment: "Pull-up bar",
    target_muscles: "Abs",
    categoryId: "core",
    muscleId: "abs",
    bodyPartId: "core",
    workoutType: "GYM",
    sets: "3",
    reps: "10–12",
    rest: "75s",
    formTips: ["Avoid swinging the body.", "Carefully lower the legs back down."],
    commonMistakes: ["Using momentum.", "Allowing the hips to move."],
    safetyTip: "Use bent knees if straight-leg raises are too difficult.",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    description: "Rotate your torso to work the obliques.",
    instructions: "Sit tall, lift your feet slightly, and twist from side to side.",
    difficulty: "Intermediate",
    equipment: "Bodyweight or light weight",
    target_muscles: "Obliques",
    categoryId: "core",
    muscleId: "obliques",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "20 total",
    rest: "45s",
    formTips: ["Keep your back straight.", "Rotate from the ribs."],
    commonMistakes: ["Rounding the spine.", "Moving too quickly."],
    safetyTip: "Keep the motion controlled and avoid jerky swings.",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    description: "Hold a side position to train the obliques and shoulder stability.",
    instructions: "Keep a straight line from head to feet while bracing the core.",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    target_muscles: "Obliques",
    categoryId: "core",
    muscleId: "obliques",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "30–45s each side",
    rest: "45s",
    formTips: ["Keep hips lifted.", "Stack the shoulders and feet."],
    commonMistakes: ["Dropping the hips.", "Twisting the torso."],
    safetyTip: "Maintain a neutral neck and avoid shoulder strain.",
  },
  {
    id: "woodchopper",
    name: "Cable Woodchopper",
    description: "Rotate across your body with cable resistance to target the obliques.",
    instructions: "Pull the cable diagonally downward while pivoting on your feet.",
    difficulty: "Intermediate",
    equipment: "Cable machine",
    target_muscles: "Obliques",
    categoryId: "core",
    muscleId: "obliques",
    bodyPartId: "core",
    workoutType: "GYM",
    sets: "3",
    reps: "10–12 each side",
    rest: "60s",
    formTips: ["Keep the core tight.", "Rotate through the torso, not just the arms."],
    commonMistakes: ["Using the arms too much.", "Losing alignment in the hips."],
    safetyTip: "Keep the movement smooth and under control.",
  },
  {
    id: "back-extension",
    name: "Back Extension",
    description: "Lift your torso with a controlled hinge to train the lower back.",
    instructions: "Use a hyperextension bench or roman chair to raise your upper body.",
    difficulty: "Intermediate",
    equipment: "Back extension bench",
    target_muscles: "Lower Back",
    categoryId: "core",
    muscleId: "lower-back",
    bodyPartId: "core",
    workoutType: "GYM",
    sets: "3",
    reps: "10–15",
    rest: "60s",
    formTips: ["Keep the spine neutral.", "Lift using the lower back and glutes."],
    commonMistakes: ["Hyperextending at the top.", "Using momentum."],
    safetyTip: "Stop if you feel pressure in the lower spine.",
  },
  {
    id: "bird-dog",
    name: "Bird-Dog",
    description: "Extend opposite arm and leg to build lower-back stability.",
    instructions: "Keep your back flat while reaching opposite hand and foot away.",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    target_muscles: "Lower Back",
    categoryId: "core",
    muscleId: "lower-back",
    bodyPartId: "core",
    workoutType: "HOME",
    sets: "3",
    reps: "10 each side",
    rest: "45s",
    formTips: ["Keep your hips square.", "Move slowly with control."],
    commonMistakes: ["Arching the lower back.", "Raising the leg too high."],
    safetyTip: "Stop if your lower back starts to fatigue excessively.",
  },
];

export async function fetchExerciseCategories() {
  return EXERCISE_CATEGORIES;
}

function normalizeId(value) {
  return String(value || "").trim().toLowerCase();
}

function normalizeWorkoutType(value) {
  return String(value || "").trim().toUpperCase();
}

export async function fetchExerciseCategoryById(categoryId) {
  const normalizedCategoryId = normalizeId(categoryId);
  return EXERCISE_CATEGORIES.find((category) => normalizeId(category.id) === normalizedCategoryId) || null;
}

export async function fetchMusclesByCategory(categoryId) {
  const normalizedCategoryId = normalizeId(categoryId);
  return EXERCISE_MUSCLES.filter((muscle) => normalizeId(muscle.categoryId) === normalizedCategoryId);
}

export async function fetchMuscleById(muscleId) {
  const normalizedMuscleId = normalizeId(muscleId);
  return EXERCISE_MUSCLES.find((muscle) => normalizeId(muscle.id) === normalizedMuscleId) || null;
}

export async function fetchBodyParts() {
  // Prefer centralized bodyParts data when available
  if (Array.isArray(CENTRAL_BODY_PARTS) && CENTRAL_BODY_PARTS.length) {
    return CENTRAL_BODY_PARTS;
  }
  return LEGACY_BODY_PARTS;
}

export async function fetchBodyPartById(bodyPartId) {
  if (Array.isArray(CENTRAL_BODY_PARTS) && CENTRAL_BODY_PARTS.length) {
    return CENTRAL_BODY_PARTS.find((part) => part.id === bodyPartId) || null;
  }
  return LEGACY_BODY_PARTS.find((part) => part.id === bodyPartId) || null;
}

function prioritizeSupportedExercises(exercises) {
  return [...exercises].sort((a, b) => {
    const order = { "push-up": 0, squat: 1 };
    const aRank = order[normalizeId(a.id)] ?? 2;
    const bRank = order[normalizeId(b.id)] ?? 2;
    return aRank - bRank;
  });
}

export async function fetchExercises(bodyPartId, workoutType) {
  // Prefer centralized exercises when available
  let exercises = Array.isArray(CENTRAL_EXERCISES) && CENTRAL_EXERCISES.length ? [...CENTRAL_EXERCISES] : [...EXERCISES];

  if (bodyPartId) {
    const normalizedBodyPartId = normalizeId(bodyPartId);
    exercises = exercises.filter((exercise) => {
      const matchesBodyPart = normalizeId(exercise.bodyPart || exercise.bodyPartId || exercise.muscleId || exercise.categoryId) === normalizedBodyPartId;
      return matchesBodyPart;
    });
  }

  if (workoutType) {
    const normalizedWorkoutType = normalizeWorkoutType(workoutType);
    exercises = exercises.filter((exercise) => normalizeWorkoutType(exercise.workoutType || exercise.workoutType) === normalizedWorkoutType);
  }

  return prioritizeSupportedExercises(exercises);
}

export async function fetchExercisesBySelection(categoryId, muscleId, workoutType) {
  const pool = Array.isArray(CENTRAL_EXERCISES) && CENTRAL_EXERCISES.length ? CENTRAL_EXERCISES : EXERCISES;
  const normalizedCategoryId = normalizeId(categoryId);
  const normalizedMuscleId = normalizeId(muscleId);
  const normalizedWorkoutType = normalizeWorkoutType(workoutType);

  return prioritizeSupportedExercises(
    pool.filter(
      (exercise) =>
        normalizeId(exercise.categoryId || exercise.bodyPart) === normalizedCategoryId &&
        normalizeId(exercise.muscleId || exercise.bodyPart) === normalizedMuscleId &&
        normalizeWorkoutType(exercise.workoutType) === normalizedWorkoutType
    )
  );
}

export async function fetchExerciseById(exerciseId) {
  if (Array.isArray(CENTRAL_EXERCISES) && CENTRAL_EXERCISES.length) {
    const found = CENTRAL_EXERCISES.find((exercise) => String(exercise.id) === String(exerciseId));
    if (found) return found;
  }
  return EXERCISES.find((exercise) => String(exercise.id) === String(exerciseId)) || null;
}
