// Database schema definitions for future Supabase tables.
// These are architectural references only; actual migrations should be created in Supabase.

export const SUPABASE_TABLES = {
  exercise_rules: {
    id: "uuid",
    exercise_id: "uuid",
    body_landmarks: "json",
    angle_rules: "json",
    common_errors: "text",
    correction_message: "text",
  },
  foods: {
    id: "uuid",
    name: "text",
    category: "text",
    serving_size: "numeric",
    serving_unit: "text",
    calories: "numeric",
    protein_g: "numeric",
    carbs_g: "numeric",
    fat_g: "numeric",
    fiber_g: "numeric",
    is_vegetarian: "boolean",
    created_at: "timestamp with time zone",
  },
  profiles: {
    id: "uuid",
    user_id: "uuid",
    name: "text",
    age: "integer",
    gender: "text",
    height_cm: "numeric",
    weight_kg: "numeric",
    goal: "text",
    activity_level: "text",
    training_days: "integer",
    created_at: "timestamp with time zone",
    updated_at: "timestamp with time zone",
  },
  meal_logs: {
    id: "uuid",
    user_id: "uuid",
    food_id: "uuid",
    meal_type: "text",
    quantity: "numeric",
    unit: "text",
    calories: "numeric",
    protein_g: "numeric",
    carbs_g: "numeric",
    fat_g: "numeric",
    logged_at: "timestamp with time zone",
    created_at: "timestamp with time zone",
  },
  water_logs: {
    id: "uuid",
    user_id: "uuid",
    amount_ml: "integer",
    logged_at: "timestamp with time zone",
    created_at: "timestamp with time zone",
  },
  progress: {
    id: "uuid",
    user_id: "uuid",
    date: "date",
    weight_kg: "numeric",
    body_fat: "numeric",
    muscle_mass: "numeric",
    calories_burned: "numeric",
    workout_type: "text",
  },
  workout_sessions: {
    id: "bigint",
    user_id: "uuid",
    workout_name: "text",
    body_part_id: "bigint",
    duration_minutes: "integer",
    calories_burned: "integer",
    total_exercises: "integer",
    completed_at: "timestamp with time zone",
    created_at: "timestamp with time zone",
  },
};
