-- Create workout_sessions table for workout history persistence.
-- Enable Row Level Security and policies for authenticated users.

create table if not exists workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid,
  workout_name text not null,
  body_part_id bigint references body_parts(id),
  duration_minutes integer not null default 0,
  calories_burned integer not null default 0,
  total_exercises integer not null default 0,
  completed_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

alter table workout_sessions enable row level security;

create policy "Authenticated users can insert their own workout sessions"
  on workout_sessions
  for insert
  with check (auth.uid() = user_id);

create policy "Authenticated users can read their own workout sessions"
  on workout_sessions
  for select
  using (auth.uid() = user_id);
