-- Create exercise_rules table for AI form detection rules.
create table if not exists exercise_rules (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null,
  rule_type text not null,
  min_angle integer,
  max_angle integer,
  feedback text not null,
  created_at timestamp with time zone default now()
);

alter table exercise_rules enable row level security;

create policy "Authenticated users can read exercise rules"
  on exercise_rules
  for select
  using (true);

create policy "Authenticated users can insert exercise rules"
  on exercise_rules
  for insert
  with check (true);
